### PR TITLE
Add a .gitignore

### PR DESCRIPTION
**Pull request by jayrbolton**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Please don't add gitignore files to the repos - they become a huge mess of everyone's personal cruft.

**Comment by jayrbolton** [comment]
Everything in this gitignore was specific to this project. None of it was my personal configuration.

I've definitely never seen this practice of not committing a gitignore. I have always seen a base gitignore  that includes basic build and config files for the project. It's more inconvenient to me to try to run a project, get a bunch of generated files that cause git diffs, and then having to manage a global gitignore for dozens of individual projects

**Comment by MrCreosote** [comment]
> Everything in this gitignore was specific to this project. None of it was my personal configuration.

I know, but in practice everyone starts adding their own personal stuff, sometimes by accident because they have changes in their local gitignore and do `git add .`. You have to manually remember *not* to add your changes to the gitignore for every update. It becomes a huge pain.

> It's more inconvenient to me to try to run a project, get a bunch of generated files that cause git diffs, and then having to manage a global gitignore for dozens of individual projects

Why would you put everything in a global gitignore? Just use project or folder specific ones. It takes me a few seconds per project and then it's done forever.

**Comment by MrCreosote** [comment]
How about this - add a `.gitignore.example` (or something) file, and on the first step of `ant build` copy it to `.gitignore` if `.gitignore` doesn't exist.

The only issue would be if that file changed the changes wouldn't get applied if you already have a gitignore.

**Comment by MrCreosote** [comment]
This is how I do it:
```
~/localgit/AssemblyHomologyService$ find -type f -name ".gitignore"
./jettybase/webapps/.gitignore
./.gitignore
~/localgit/AssemblyHomologyService$ cat .gitignore
/bin/
/classes/
/dist/
/docs/
/assembly_homology
/assembly_homology.cfg
/deploy.cfg
/test-reports/
/test.cfg
/temp_test_delete/
~/localgit/AssemblyHomologyService$ cat jettybase/webapps/.gitignore 
/ROOT.war

~$ cat .gitignore_global
.classpath
.project
.pydevproject
.gitignore
.includepath
*.pyc
*.pyo
*~
*.bak-*
.settings
*.class

```

**Pull request closed without merging**
